name       : embree
version    : 3.12.1
release    : 3
source     :
    - https://github.com/embree/embree/archive/v3.12.1.tar.gz : 0c9e760b06e178197dd29c9a54f08ff7b184b0487b5ba8b8be058e219e23336e
license    : Apache-2.0
component  : programming.library
summary    : High Performance Ray Tracing Kernels
description: |
    Intel® Embree is a collection of high-performance ray tracing kernels, developed at Intel. The target users of Intel® Embree are graphics application engineers who want to improve the performance of their photo-realistic rendering application by leveraging Embree's performance-optimized ray tracing kernels. The kernels are optimized for the latest Intel® processors with support for SSE, AVX, AVX2, and AVX-512 instructions. Intel® Embree supports runtime code selection to choose the traversal and build algorithms that best matches the instruction set of your CPU. We recommend using Intel® Embree through its API to get the highest benefit from future improvements.
builddeps  :
    - intel-tbb-devel
    - ispc
clang      : yes # gcc uses a stupid amount of memory.
setup      : |
    %cmake_ninja \
      -DEMBREE_ISA_AVX512SKX=ON \
      -DEMBREE_ISA_AVX512KNL=OFF \
      -DEMBREE_TUTORIALS=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -r $installdir/usr/share/doc/
